### PR TITLE
Framework: Try Autoprefixer for Babel

### PR DESCRIPTION
**Pull request by gziolo**
Tests #1057.

This PR tries to validate if using [babel-preset-env](https://github.com/babel/babel-preset-env) would help to reduce bundles size for Delphin.

### 2 latest Chrome and Firefox versions

```js
{
  "presets": [
    [ "env", {
      "targets": {
        "browsers": [ "last 2 Chrome versions", "last 2 Firefox versions" ]
      },
      "useBuiltIns": true
    } ],
    "react",
    "stage-1"
  ]
}
```

>              Asset      Size            Chunks  Chunk Names
>     0.bundle.js   258 kB       0  [emitted]
>     1.bundle.js   216 kB       1  [emitted]
>     2.bundle.js  86.7 kB       2  [emitted]
>     3.bundle.js  88.8 kB       3  [emitted]
>       bundle.js  1.54 MB       4  [emitted]  main
>     0.bundle.js.map   330 kB       0  [emitted]
>     1.bundle.js.map   296 kB       1  [emitted]
>     2.bundle.js.map   109 kB       2  [emitted]
>     3.bundle.js.map   124 kB       3  [emitted]
>     bundle.js.map  1.97 MB       4  [emitted]  main
>  [298] ./webpack.client.config.js 2.93 kB {4} [built]
>  [742] ./webpack.base.config.js 1.7 kB {4} [built]
>     + 915 hidden modules
> ✨  Done in 16.14s.
> ✨  Done in 37.86s.

### 2 latest browser versions
```js
{
  "presets": [
    [ "env", {
      "targets": {
        "browsers": [ "last 2 versions" ],
        "node": "current"
      },
      "useBuiltIns": true
    } ],
    "react",
    "stage-1"
  ]
}
```

>           Asset     Size  Chunks             Chunk Names 
>      0.bundle.js   286 kB       0  [emitted]
>      1.bundle.js   243 kB       1  [emitted]
>      2.bundle.js  93.9 kB       2  [emitted]  
>      3.bundle.js   103 kB       3  [emitted]  
>      bundle.js  1.58 MB       4  [emitted]  main
>      0.bundle.js.map   331 kB       0  [emitted]  
>      1.bundle.js.map   297 kB       1  [emitted]  
>      2.bundle.js.map   109 kB       2  [emitted]  
>      3.bundle.js.map   124 kB       3  [emitted]  
>      bundle.js.map  1.97 MB       4  [emitted]  main
>  [298] ./webpack.client.config.js 2.93 kB {4} [built]
>  [742] ./webpack.base.config.js 1.7 kB {4} [built]
>     + 915 hidden modules
> ✨  Done in 17.70s.
> ✨  Done in 42.09s.

### CODE REVIEW

**Comment by DanReyLop** [comment]
I *think* the `latest 2 versions` includes IE11 and IE10. If we don't support IE10, you can add explicitly `not IE 10`, that should help a bit :)

**Comment by gziolo** [comment]
@DanReyLop, there is more that IE10 and IE11, there are also 2 latest versions of iOS Safari and something targeting Android, too. It's more complicated ;)

**Comment by DanReyLop** [comment]
Sure, but what I mean is you can do `"browsers": [ "last 2 versions", "not ie10" ]` and that would exclude IE10. Making an educated guess, I would say IE10 is the reason why this PR didn't have much impact.

**Comment by gziolo** [comment]
I tried that already, it doesn't change much. You need to target chrome and ff to see any difference.

**Comment by gziolo** [comment]
After reading http://www.2ality.com/2017/02/babel-preset-env.html I discovered that `modules` flag needs to be set to false to take advantage of Webpack tree shaking 😃

**Comment by gziolo** [comment]
When I change babel config to:
```js
{
  "presets": [
    [ "env", {
      "targets": {
        "browsers": [ "last 2 versions" ],
        "node": "current"
      },
      "debug": true,
      "modules": false,
      "useBuiltIns": true
    } ],
    "react",
    "stage-1"
  ]
}
```

I see the following error:

> ERROR in ./client/index.js
> Module parse failed: /Users/gziolo/PhpstormProjects/delphin/node_modules/react-hot-loader/index.js!/Users/gziolo/PhpstormProjects/delphin/node_modules/babel-loader/lib/index.js!/Users/gziolo/PhpstormProjects/delphin/client/index.js 'import' and 'export' may only appear at the top level (6:0)
> You may need an appropriate loader to handle this file type.
> | 
> | // External dependencies
> | import { applyMiddleware, combineReducers, createStore } from 'redux';
> | import { browserHistory } from 'react-router';
> | import createLogger from 'redux-logger';
>  @ multi app

I don't have enough time to investigate it further today.

**Comment by DanReyLop** [comment]
I think this may be the problem: https://github.com/Automattic/delphin/blob/master/package.json#L119

You're using an old (and beta) version of WebPack 2, who knows what its bugs are :)

We've succesfully added WebPack2 to `woocommerce-services`, you'll need to change some stuff on the webpack config, this guide was amazing for that: https://webpack.js.org/guides/migrating/

Don't expect much benefit from tree-shaking though.

**Comment by gziolo** [comment]
Many thanks for hints!
To be honest I don't expect too much. I'm just curious how it works and thus exploring different configurations ;) There is so much buzz about tree-shaking, webpack, etc. Delphin is relatively small codebase at the same working perfectly fine on production. Therefore it is great for such explorations :)

**Comment by gziolo** [comment]
I'm also afraid that changing babel configuration may break Jest tests, because Node 6.x doesn't support import/export :P
It looks like I will leave my exercises until Webpack gets updated to the latest version.

**Pull request closed without merging**
